% demo_eyeBlinkRemoval.m
% Diagnostic script: visualise which ICA components are identified as eye-blink
% artifacts and compare the EEG signal before and after removal.
%
% Requires global_ica_parameters.mat (generated by 01_fitGlobalICA.m).
% Edit the 'file' variable below to point to any OA recording.

addpath('pca_ica\');

%% CONFIGURATION
file = '20240227124925_PRE_Control_72_GS_OA.edf';  % <-- change as needed
band = {0.1, 30};
fs   = 500;

%% LOAD & PREPROCESS
load('global_ica_parameters.mat');

S          = readEDF(file);
X          = StructToDouble(S);
X          = X(1:end-3, 2000:74901);  % drop edges & accel channels
X          = applyPassBand(X, fs, band);

% Centre · Scale · Whiten
[Zc, mu] = centerRows(X);       % mu    : (20 x 1)
sigma    = std(X, 1, 2);        % sigma : (20 x 1)
[Zw, T]  = whitenRows(Zc./sigma);

% ICA — warm-started from global model
W_init         = GlobalParams.W_OA;
[~, W_fit, ~, ~, ~] = fastICA(Zw, 10, 'negentropy', 1, W_init);
Zica           = W_fit * Zw;    % (10 x N)

%% COMPONENT SCORING — correlation with frontal average (Fp1 & Fp2)
n_components = size(Zica, 1);

avg_Fp      = mean(Zw([7, 8], :), 1);
avg_Fp_norm = (avg_Fp - mean(avg_Fp)) / std(avg_Fp);

correlations = zeros(n_components, 1);
for i = 1:n_components
    comp_norm       = (Zica(i,:) - mean(Zica(i,:))) / std(Zica(i,:));
    corr_mat        = corrcoef(comp_norm, avg_Fp_norm);
    correlations(i) = abs(corr_mat(1, 2));  % absolute: ICA sign is arbitrary
end

%% ARTIFACT REMOVAL
[~, idx_ranking] = sort(correlations, 'descend');
comps_to_remove  = idx_ranking(1:2);   % top 2 components by correlation

Zica_clean                    = Zica;
Zica_clean(comps_to_remove,:) = 0;

% Reconstruct: de-mix → de-whiten → de-scale → de-centre
Z_back = pinv(W_fit) * Zica_clean;
Zc_rec = pinv(T) * Z_back;
X_filt = (Zc_rec .* sigma) + mu;

%% FIGURE — publication-ready
t = (0:size(X, 2)-1) / fs;

figure('Color', 'w', 'Units', 'normalized', 'Position', [0.15 0.15 0.45 0.7]);

% Subplots 1 & 2: rejected independent components
for i = 1:2
    idx      = idx_ranking(i);
    sig_norm = (Zica(idx,:) - mean(Zica(idx,:))) / std(Zica(idx,:));

    subplot(3, 1, i);
    plot(t, sig_norm, 'Color', [0.8500 0.3250 0.0980], 'LineWidth', 1);
    ylabel(sprintf('IC %d (a.u.)', idx), 'FontWeight', 'bold');
    title(sprintf('Rejected Component | |r| = %.3f', correlations(idx)), 'FontSize', 10);
    grid on;
    set(gca, 'TickDir', 'out', 'Box', 'off', 'XTickLabel', []);
    xlim([t(1) t(end)]);
end

% Subplot 3: before / after comparison on averaged Fp1 & Fp2
subplot(3, 1, 3);
hold on;
plot(t, mean(X(7:8,:),     1), 'Color', [0.7 0.7 0.7],    'LineWidth', 1,   'DisplayName', 'Original (Fp1 & Fp2)');
plot(t, mean(X_filt(7:8,:),1), 'Color', [0 0.4470 0.7410], 'LineWidth', 1.2, 'DisplayName', 'ICA Cleaned');
title('Frontal EEG: Before and After Blink Artifact Removal', 'FontSize', 11, 'FontWeight', 'bold');
ylabel('Amplitude (\muV)', 'FontWeight', 'bold');
xlabel('Time (s)',          'FontWeight', 'bold');
legend('Location', 'northeast', 'Box', 'off');
grid on;
set(gca, 'TickDir', 'out', 'Box', 'off');
xlim([t(1) t(end)]);
